name: OriginsSpawn
version: '${project.version}'
main: origins.locations.main.MainLocations
api-version: 1.19
authors: [Dimensoes]
commands:
  inicio:
    description: "Teletransporta para o ponto de origem."